### ISSUE TITLE
Problem with cocoapod download 

### ISSUE THREAD

**Issue by vergisf** [daoseng33/DAOSearchBar#3]
I'm trying to download the component, but the following error is occurring: Remote branch 1.0.4 not found in upstream origin

Tanks

**Comment by daoseng33** [comment]
Hello, I fixed the problem, plz try it again, thanks

**Comment by vergisf** [comment]
Hello, the download problem has been fixed. But I identified a problem, where in Pods when downloading, the DAOSearchBar class is without the open, and I can not access it.
Thanks
